Add wget as an option to install
In some case, curl unable to perform as nodejs uses Cloudflare to protect. We need an option to install and in this case I use wget.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -91,8 +91,19 @@ get_nodejs_machine_hardware_name() {
   echo "$cpu_type"
 }
 
+download_file_with_curl() {
+  local download_url="$1"
+  local download_path="$2"
 
-download_file() {
+  STATUSCODE=$(curl --write-out "%{http_code}" -Lo "$download_path" -C - "$download_url")
+
+  if test $STATUSCODE -eq 404; then
+    echo "Binaries were not found. Full version must be specified, not just major version."
+    exit 1
+  fi
+}
+
+download_file_with_wget() {
   local download_url="$1"
   local download_path="$2"
 
@@ -104,6 +115,16 @@ download_file() {
   fi
 }
 
+download_file() {
+  local download_url="$1"
+  local download_path="$2"
+
+  if [ -n "${DOWNLOADER+1}" ]; then
+    download_file_with_wget  "${download_url}" "${download_path}"
+  else
+    download_file_with_curl "${download_url}" "${download_path}"
+  fi
+}
 
 get_archive_file_name() {
   local install_type="$1"
